name: "main pull request"
on:
  pull_request:
    branches: [main]

jobs:
  go-staticcheck:
    name: "Golang static testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: "1.21.x"
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.6"
          install-go: false
          working-directory: ./src/backend/consumer
  ts-staticcheck:
    name: "Typescript static testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install
        working-directory: src/frontend/
      - run: npm run lint
        working-directory: src/frontend/
