name: "Robot Framework integration tests"
on: push

jobs:
  test:
    name: "run integration tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install zbctl
        run: |
          npm i -g zbctl
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: src/test/integration_test
      - name: Docker compose up
        run: |
          docker-compose up -d
      - name: Run tests
        run: |
          robot --outputdir output/ test_suites/
        working-directory: src/test/integration_test
      - name: Docker compose down
        run: |
          docker-compose down
        if: always()
      - name: Upload results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: robot-results
          path: src/test/integration_test/output/
      - name: Send results to commit
        uses: joonvena/robotframework-reporter-action@v2.3
        if: always()
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: src/test/integration_test/output/
    